[package]
name = "short"
version = "0.2.0"
edition = "2024"

[dependencies]
ureq = { version = "3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
duration-str = "0.21.0"
